### ISSUE TITLE
Improve you responses

### ISSUE THREAD

**Issue by ElAmen** [prinx/dotnet-shopping-cart#1]
Try to make you response the same format: 
ie:
{
   "success": true,
   "message": "Item added to cart", //this could be nice error messages in case of failure
   "data": {
             .....
         }
}

Also avoid using SingleOrDefault, do a little research about FindAsync and FirstOrDefaultAsync and use the one that makes  more sense

**Comment by ElAmen** [comment]
If you can also research and add swagger example to your code it will be dope

**Comment by ElAmen** [comment]
Boss Prince can you look into how to create a kafka consumer and producer and write a basic very simple project about the 2 concepts

**Comment by prinx** [comment]
> Boss Prince can you look into how to create a kafka consumer and producer and write a basic very simple project about the 2 concepts

Of course! I will look into that and share as soon as possible.

**Comment by prinx** [comment]
> If you can also research and add swagger example to your code it will be dope

Yes. Swagger was added by this commit 6b81c63e9882373a17ed548cab047f68d3f7aacc

**Comment by prinx** [comment]
> Try to make you response the same format:
> ie:
> {
> "success": true,
> "message": "Item added to cart", //this could be nice error messages in case of failure
> "data": {
> .....
> }
> }
> 
> Also avoid using SingleOrDefault, do a little research about FindAsync and FirstOrDefaultAsync and use the one that makes more sense

Thanks!!! I will push an update very soon.

**Comment by prinx** [comment]
Issue resolved. Check commit 0f059603600337dda16aaeca7066256e65eff3da and c24cc6bff5011629c1f2d0e4f9e2ecac6808c05f

> 
> 
> Try to make you response the same format:
> ie:
> {
> "success": true,
> "message": "Item added to cart", //this could be nice error messages in case of failure
> "data": {
> .....
> }
> }
> 
> Also avoid using SingleOrDefault, do a little research about FindAsync and FirstOrDefaultAsync and use the one that makes more sense

Resolved with commits 0f059603600337dda16aaeca7066256e65eff3da and c24cc6bff5011629c1f2d0e4f9e2ecac6808c05f
